name: ws-react-sdk CD

on:
  push:
    branches:
      - master
      - develop

jobs:
  publish:
    name: checkout-build-commit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
      - uses: actions/checkout@v2
      - name: Get branch name
        id: vars
        run: echo ::set-output name=branch::${GITHUB_REF#refs/*/}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn
      - name: Bump version
        run: |
          git config --global user.email "git@wednesday.is"
          git config --global user.name "Gitflow"
          npm version patch -m 'Bump up'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
